export enum GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}
export enum EDUCATION_LEVEL {
  MID_SCHOOL = 'MID_SCHOOL',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  UNDERGRADUATE = 'UNDERGRADUATE',
  POSTGRADUATE = 'POSTGRADUATE',
  WORKING_PROFESSIONAL = 'WORKING_PROFESSIONAL',
}